# Generated by Django 2.1.2 on 2018-11-01 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simpatik', '0004_auto_20181101_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('booked_quantity', models.IntegerField()),
                ('item_created_dt', models.DateTimeField(auto_now_add=True)),
                ('item_updated_dt', models.DateTimeField(null=True)),
                ('item_created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to=settings.AUTH_USER_MODEL)),
                ('item_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='simpatik.Location')),
                ('item_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=30)),
                ('tr_created_dt', models.DateTimeField(auto_now_add=True)),
                ('tr_updated_dt', models.DateTimeField(null=True)),
                ('tr_created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('tr_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.PositiveIntegerField(default=0)),
                ('detail_qty', models.PositiveIntegerField(default=0)),
                ('tr_dtl_updated_dt', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='simpatik.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='detail_sts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='simpatik.TransactionStatus'),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='details', to='simpatik.Item'),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='tr_dtl_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='transaction_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='simpatik.Transaction'),
        ),
    ]
