# Generated by Django 2.1.2 on 2018-11-09 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simpatik', '0006_auto_20181103_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_qty', models.PositiveIntegerField(default=0)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='carts', to='simpatik.Item')),
                ('cart_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
