# Generated by Django 2.1.3 on 2018-11-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpatik', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item_qty',
            field=models.PositiveIntegerField(),
        ),
    ]
