# Generated by Django 2.1.3 on 2018-11-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpatik', '0008_auto_20181110_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item_qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
