# Generated by Django 2.1.3 on 2018-11-17 02:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpatik', '0010_auto_20181110_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetail',
            name='detail_sts',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_sts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='simpatik.TransactionStatus'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item_qty',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Tidak boleh kurang dari 1')]),
        ),
    ]
